version: '3'

services:
  server:
    build: ./signals-server
    environment:
      - VIRTUAL_HOST=api.signals.local
      - UI_HOST=signals.local
    networks:
      - default
      - proxy

  ui:
    build: ./signals-ui
    environment:
      - VIRTUAL_HOST=signals.local
      - VIRTUAL_PORT=8080
      - SERVER_HOST=api.signals.local
    networks:
      - default
      - proxy

  proxy:
    image: jwilder/nginx-proxy
    ports:
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost.d:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - ssl-server
      - ssl-ui

  ssl-server:
    image: paulczar/omgwtfssl
    volumes:
      - certs:/certs
    environment:
      - SSL_SUBJECT=api.signals.local
      - SSL_KEY=/certs/api.signals.local.key
      - SSL_CSR=/certs/api.signals.local.csr
      - SSL_CERT=/certs/api.signals.local.crt

  ssl-ui:
    image: paulczar/omgwtfssl
    volumes:
      - certs:/certs
    environment:
      - SSL_SUBJECT=signals.local
      - SSL_KEY=/certs/signals.local.key
      - SSL_CSR=/certs/signals.local.csr
      - SSL_CERT=/certs/signals.local.crt

volumes:
  certs:
  vhost.d:

networks:
  proxy:
