name: Docker

on:
  push:
    branches:
      - master

    tags:
      - v*

env:
  BACKEND_IMAGE_NAME: pope-server

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build backend image
        run: docker build . --tag backend
        working-directory: ./backend

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USER_NAME }} --password-stdin

      - name: Push backend image
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          docker tag backend ${{ secrets.DOCKER_HUB_USER_NAME }}/$BACKEND_IMAGE_NAME:$VERSION
          docker push ${{ secrets.DOCKER_HUB_USER_NAME }}/$BACKEND_IMAGE_NAME:$VERSION
